name: link_preview_example
description: A Flutter package to render a link preview inspired by link_previewer
version: 0.0.1
author: Jamal Shr <me@shrjamal.com>
homepage: https://github.com/shrjamal/link-preview

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  link_preview:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

