name: link_preview_example
description: A Flutter package to render a link preview inspired by link_previewer
version: 0.0.1
homepage: https://github.com/shrjamal/link-preview
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  link_preview:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
