name: link_preview
description: A Flutter package to render a link preview inspired by link_previewer
version: 0.0.1
author: Jamal Shr <me@shrjamal.com>
homepage: https://github.com/shrjamal/link-preview

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+3
  http: ^0.12.0+2
  url_launcher: ^5.1.1
  cached_network_image: ^2.0.0
  freezed_annotation: ^0.7.1
  shared_preferences: ^0.5.6+3
  mime: ^0.9.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.10.4
  build_runner: ^1.8.1
  json_serializable: ^3.3.0

flutter: